### ISSUE TITLE
density method gives aberrant output, apparently when K=1 and returned lambda=1

### ISSUE THREAD

**Issue by glewen** [RGLab/flowClust#11]
Occasionally, the density computed for a flowClust object with K=1 is shifted away from the cluster center.  So far, this appears to happen when the value of lambda returned by flowClust =1.  When lambda is not equal to 1, the density contours seem reasonable.  (Simple code used to generate data follows.)  I can provide the input data (xy) upon request.  

fc<-flowClust(xy,K=1)
fc.dens<-density(fc,data=xy)
plot(fc,data=xy)
contour(fc.dens@dx,fc.dens@dy,fc.dens@value,add=T)

![capture](https://cloud.githubusercontent.com/assets/10406531/7844368/e3333866-047d-11e5-8443-1ecdb92d0479.PNG)

**Comment by gfinak** [comment]
@glewen  
I've pushed a fix. This is a longstanding issue that keeps cropping up in various places. Thanks for bringing this one to our attention, we thought we'd caught them all. It has to do with how the box-cox transform is handled when lambda=1.

**Comment by glewen** [comment]
Thanks for the quick response!  Very much appreciated.
