### ISSUE TITLE
flowClust segfault on windows

### ISSUE THREAD

**Issue by mikejiang** [RGLab/flowClust#14]
`bioc` devel reports package install [error](http://bioconductor.org/checkResults/devel/bioc-LATEST/flowClust/moscato2-checksrc.html)

I've verified it is reproducible on  `R arch i386`, but works fine on `x64`.

`gdb` shows it is [this](https://github.com/RGLab/flowClust/blob/trunk/src/flowClust.c#L138)  exact line that fails. And here is the variable context in `gdb` right before it crashes 
```bash
Breakpoint 1, flowClust (y=0xc4b20b8, ly=0xc4bfa08, py=0xc4bf9e8,  ...)
    at flowClust.c:138
138                     rowYTrans = gsl_matrix_row(YTrans, i);
(gdb) p *transform
$1 = 1
(gdb) p *ly
$2 = 1509
(gdb) p *py
$3 = 2
(gdb) p *YTrans
$4 = {size1 = 1509, size2 = 2, tda = 2, data = 0x9374438, block = 0x9374418,
  owner = 1}
(gdb) p i
$5 = 5
(gdb) n

Program received signal SIGSEGV, Segmentation fault.
```
 The [doc](https://www.gnu.org/software/gsl/manual/html_node/Creating-row-and-column-views.html#Creating-row-and-column-views) for `gsl_matrix_row` says it should be safe even if the index is out of range. 
I've looked at the code that involves `gsl_matrix` **YTrans** and there is no indication that it was corrupted before this call.  

And it consistently crashes at iteration `i = 5`. (even in the pure R session without `gdb`).

So I don't have clues where could go wrong at moment. Could it be problem of prebuilt system library (e.g. libgsl) on arch i386 since they were compiled by a new toolchain mentioned [here](https://github.com/Bioconductor/Bioconductor/blob/master/documentation/new-toolchain-setup.md)

**Comment by mikejiang** [comment]
Any thoughts, @dtenenba?

**Comment by dtenenba** [comment]
Actually, I don't think GSL was rebuilt under the new toolchain; the same [local323.zip](http://www.stats.ox.ac.uk/pub/Rtools/libs.html) is used as was used under the old toolchain. 
As I understand it, only system dependencies that contain C++ need to be rebuilt. 

However, perhaps there are some issues with it and perhaps it should be rebuilt under the new toolchain. There are other packages (such as `flowPeaks`) that also use GSL and have issues on windows i386 only.

Any thoughts @jimhester @mtmorgan ?

I can look into building gsl from source on windows--anyone know what's involved with that?

Also, just out of curiosity @mikejiang how did you end up getting gdb to work on windows? I'd like to know for future reference.

**Comment by dtenenba** [comment]
So I just rebuilt libgsl.a -- just the i386 version, and rebuilt flowClust against it. This time `example(flowClust)` works!


The [flowPeaks example](https://www.bioconductor.org/checkResults/devel/bioc-LATEST/flowPeaks/moscato2-checksrc.html) that also failed is now passing.


So I guess this means that we can't use the libgsl.a (i386 version) that is supplied by local323.zip. Is that right @jimhester ? I can provide the one I built (and the instructions I used to build it). For now I guess I will add those instructions to the [toolchain page](https://github.com/Bioconductor/Bioconductor/blob/master/documentation/new-toolchain-setup.md).

But it sounds like CRAN probably needs to provide an updated `lib\i386\libgsl.a` to overwrite the one in local323 zip if the new toolchain is being used? Maybe it's time for a local330.zip?

@jeroenooms

**Comment by dtenenba** [comment]
Updated the [toolchain page](https://github.com/Bioconductor/Bioconductor/blob/master/documentation/new-toolchain-setup.md#flowclust-flowpeaks) 
with a link to the newly built libgsl.a and instructions on how to build it.

**Comment by jeroenooms** [comment]
We are maintaining static libraries for windows on https://github.com/rwinlib. You can add `libgsl` or other libraries if there if you'd like. 

I recommend designing your package to automatically download and link the static libraries when building the package on windows, rather than making assumptions about what is available on the build server. See the `Makevars.win` from [hunspell](https://github.com/cran/hunspell/blob/master/src/Makevars.win) or [V8](https://github.com/cran/hunspell/blob/master/src/Makevars.win) for some examples on how to use the `COMPILED_BY` variable to make this work with both toolchains.

**Comment by dtenenba** [comment]
Thanks @jeroenooms , I will do that. 

Also thanks for the suggestion about changing package design, I will pass that on to Bioconductor package maintainers. However, there are still many CRAN and Bioconductor packages that do not do things this way, and rely on the libraries in local323 (or, as I just discovered, in the case of the `tiff` package, download pre-built (and broken under the new toolchain) libraries from some URL).

So it seems that we will need to get CRAN to change their build machine (assuming that they use a separate machine for builds against the new toolchain) to include newly built versions of some of these libraries. 

Also, my version of R returns an empty string for `R CMD config COMPILED_BY`; what can I do about that?

```
C:\>R CMD config COMPILED_BY


C:\>R -q -e "sessionInfo()"
> sessionInfo()
R version 3.3.0 alpha (2016-03-28 r70390)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server 2008 R2 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252
[2] LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base
```

**Comment by mikejiang** [comment]
> how did you end up getting gdb to work on windows

@dtenenba ,  Here is the procedures you need to follow:
1. change optimization from `-O3` to `-O0` for `CFLAGS` in `$R_HOME/etc/i386/Makeconf`
2. add `PKG_CFLAGS = -ggdb` in package `Makevars.win`
3. install package with option `--debug` (e.g. `R CMD INSTALL flowClust --debug --preclean`)
4. run gdb , e.g. `gdb /path/to/R-3.3.0beta/bin/i386/Rgui.exe`
5. in Rgui, use the ‘Misc|Break to debugger’ menu item after package DLL is loaded.
6. help gdb to locate the dll using `file` command e.g. `file $R_LIBS/flowClust/libs/i386/flowClust.dll`
7. then gdb can load symbol table without problems

In theory, first two steps could have been done in one file `$HOME/.R/Makevars.win` through `CFLAGS`, however it didn't work for me somehow.

**Comment by jeroenooms** [comment]
@dtenenba Yes, `COMPILED_BY` was introduced recently, it will be there in R 3.3.0-beta.
